### ISSUE TITLE
Scopes/namespaces

### ISSUE THREAD

**Issue by jlumpe** [bjodah/sympy#13]
It would be nice to have a class which tracks which variable names or symbols are defined within a code block. I was thinking each AST class could define which variables it depends on and which variables it exports or defines in the surrounding code block. This would be nice for raising compile (print)-time exceptions if an unknown variable is used (maybe if the user enables a "strict" option), checking if a block of assignments are in topological order, and also maybe for a printer to sanitize variable names which are not valid identifiers (I'm running into this issue right now).

I can start on this if you think it would be useful.

**Comment by bjodah** [comment]
Usually we don't store this information actively. But since we are using SymPy's `Basic` class we can use `preorder_traversal` and `postorder_traversal` to achieve the same effect. And if we want to avoid revisiting branches we can cache the result (since `Basic` and it's children are immutable and hashable).

That said, the idea of having facilities (a function maybe?) to check for validity of code (e.g. missing declaration as you mention, or invalid names) sounds like a really good idea!

**Comment by bjodah** [comment]
Closing since sympy/sympy#13100 has been merged.
