### ISSUE TITLE
codegen Matrix

### ISSUE THREAD

**Issue by stewpend0us** [bjodah/sympy#3]
So I've been trying to use codegen to try to get what I need and I just wanted to show you what I'm doing. Not sure if this is how you intended it to be used...

```python
from sympy import *
from sympy.codegen.ast import *

def make_input_var(sym, use_type):
        is_mat = hasattr(sym, 'shape') and not isinstance(sym, Indexed)
        if is_mat:
                return Pointer(sym, type=use_type, attrs=[value_const])
        return Variable(sym, type=use_type)

def do_cse(name, assignments, use_type):
        outputs = [x.lhs for x in assignments]
        rhs = [x.rhs for x in assignments]
        inputs = set()
        [inputs.update(x.free_symbols) for x in rhs]
        vinputs = [make_input_var(x,use_type) for x in inputs]
        voutputs = [Pointer(x,type=use_type) for x in outputs]
        fp = FunctionPrototype('void',name,vinputs+voutputs)
     
        replacements, reduced = cse(rhs)
        temp = [Declaration(Variable(x[0], use_type, x[1])) for x in replacements]
        rhs_new = [Assignment(*x) for x in list(zip(outputs,reduced))] 
        fd = FunctionDefinition.from_FunctionPrototype(fp,CodeBlock(*(temp+rhs_new)))

        return (fp, fd) 

(sp, cp, tau, T, t, psi) = symbols('sp cp tau T t psi')

t1 = MatrixSymbol('t1',2,1)
t2 = MatrixSymbol('t2',2,1)
inputM = MatrixSymbol('inputM',2,1)
m1 = Matrix([ [5*sp, 5*sp], [10*cp, sin(5*sp)] ])
m2 = Matrix([ 5*sp, sin(5*sp) ])
test1 = Assignment(t1, Matrix(m1*inputM))
test2 = Assignment(t2, m2) 
     
p,d = do_cse('name', [test1,test2], float32);
print(ccode(p))
print(ccode(d))

```
which returns

```c
void name(float sp, float cp, const float * inputM, float * t1, float * t2)
void name(float sp, float cp, const float * inputM, float * t1, float * t2){
   float x0 = inputM
   float x1 = x0[0]
   float x2 = 5*sp
   float x3 = x0[1]
   float x4 = sin(x2)
   t1[0] = x1*x2 + x2*x3;
   t1[1] = 10*cp*x1 + x3*x4;
   t2[0] = x2;
   t2[1] = x4;
}

```
this is what I'm after:
```c
void name(float sp, float cp, const float inputM[2], float t1[2], float t2[2]);
void name(float sp, float cp, const float inputM[2], float t1[2], float t2[2]){
   float x0 = 5*sp;
   float x1 = sin(x0);
   t1[0] = inputM[0]*x0 + x0*inputM[1];
   t1[1] = 10*cp*inputM[0] + inputM[1]*x1;
   t2[0] = x0;
   t2[1] = x1;
}
```

I think my biggest problem is the general lack of Matrix support especially in cse...but there also seem to be a couple issues with the codegen stuff:

1) Seems like there should be an "Array" and maybe "Matrix" Variable type (float my_array[7]; float my_matrix[2*4];)
2) Should Declaration inherit from Variable?
3) FunctionPrototype lines needs a ;
4) Declaration lines needs a ;

I'd be happy to help with this stuff. I miiight be able to pull off writing the "Array" class but I'm not sure I could make it print. I have no idea how to get a ; on the end of the FunctionPrototype....

**Comment by stewpend0us** [comment]
I changed the printer to get the semi-colons to show up and also figured out how to change float x0 = inputM to float * x0 = inputM which makes it work. I think i screwed up the pull request though? It seems like it just got added onto the last pull request I made?

**Comment by bjodah** [comment]
Regarding the semicolon thing. I can't remember the details, but I remember I tried to make it do the right thing in every instance but the way I remember it was that it prevented reuse of code in the CCodePrinter, so instead I opted for introducing the `Statement` node which essentially adds the semicolon (when printing C, not Fortran of course). It is possible that one could make things work without `Statement` but it was the most straightforward way then.

I modified your code slightly:
```python
from sympy import *
from sympy.codegen.ast import *
from sympy.codegen.ast import float32

def make_input_var(sym, use_type, value=None):
    is_mat = hasattr(sym, 'shape') and not isinstance(sym, Indexed)
    if is_mat:
        return Pointer(sym, type=use_type, attrs=[value_const], value=value)
    return Variable(sym, type=use_type, value=value)

def do_cse(name, assignments, use_type):
    outputs = [x.lhs for x in assignments]
    rhs = [x.rhs for x in assignments]
    inputs = list(set.union(*[x.free_symbols for x in rhs]))
    vinputs = [make_input_var(x, use_type) for x in inputs]
    voutputs = [Pointer(x, type=use_type) for x in outputs]
    fp = FunctionPrototype('void', name, vinputs+voutputs)

    replacements, reduced = cse(rhs)
    temp = [Statement(make_input_var(tok, use_type, value=expr).as_Declaration())
            for tok, expr in replacements]
    rhs_new = [Assignment(*x) for x in list(zip(outputs,reduced))]
    fd = FunctionDefinition.from_FunctionPrototype(fp,CodeBlock(*(temp+rhs_new)))
    return (Statement(fp), fd)

(sp, cp, tau, T, t, psi) = symbols('sp cp tau T t psi')

t1 = MatrixSymbol('t1',2,1)
t2 = MatrixSymbol('t2',2,1)
inputM = MatrixSymbol('inputM',2,1)
m1 = Matrix([ [5*sp, 5*sp], [10*cp, sin(5*sp)] ])
m2 = Matrix([ 5*sp, sin(5*sp) ])
test1 = Assignment(t1, Matrix(m1*inputM))
test2 = Assignment(t2, m2)

p,d = do_cse('name', [test1,test2], float32);
print(ccode(p))
print(ccode(d))
```

This gives me:
```
void name(float cp, const float * inputM, float sp, float * t1, float * t2);
void name(float cp, const float * inputM, float sp, float * t1, float * t2){
   const float * x0 = inputM;
   float x1 = x0[0];
   float x2 = 5*sp;
   float x3 = x0[1];
   float x4 = sin(x2);
   t1[0] = x1*x2 + x2*x3;
   t1[1] = 10*cp*x1 + x3*x4;
   t2[0] = x2;
   t2[1] = x4;
}
```
So we can't expect the average user to write all the machinery for this so we definitely want utility functions along the line of your `do_cse` and `make_input_var` in the `sympy.codegen` module. We just need to ensure they generalize.

Addressing some of your bullets:

1. Yes, I think we should aim for N-dimensional arrays straight away (and support column-major and row-major order). This is partly supported by the CCodePrinter. This is e.g. the test for `.codegen.ast.Element` in `test_ccode.py`: `assert ccode(Element('x', 'ij')) == 'x[i][j]'` and `assert ccode(Element('x', 'ij', strides='kl', offset='o')) == 'x[i*k + j*l + o]'`, also `Indexed` take both a `strides` and `offset` kwarg (see also `test_ccode.py`).
2. Perhaps, I tried that but Declaration might also be of a function. So variables are in some sense a subset of what declarations can be for. For convenience I added the method `as_Declaration` to `Variable`.
3. So for now those need to be wrapped in `Statement` (motivated by consistency, see below)
4. `Declaration` instances are also used in the function signature where they are comma-separated. Hence the need of `Statement`

Regarding the pull request, yes it looks like it got mixed up because I had merged master into my branch to resolve merge conflicts. Perhaps I should just merge in your test case marked with `xfail` for now?

**Comment by stewpend0us** [comment]
Totally up to you what you want to do with my pull requests. I'll see if I can undo the changes I made to the printer or just undo the commits. Appreciate you taking a look at this for me I wish I could be more helpful but I haven't been able to absorb how it all works yet. It's a ridiculously powerful tool! But also very complex (at least for me).

**Comment by bjodah** [comment]
Your feedback is most helpful. I went ahead and added your test as an "xfailing" one (for now) in sympy/sympy#13100. Feel free to open more issues as questions pop up.

**Comment by bjodah** [comment]
Closing since sympy/sympy#13100 has been merged.
