### ISSUE TITLE
Element Declaration

### ISSUE THREAD

**Issue by stewpend0us** [bjodah/sympy#5]
Can't figure out how to get an Element Declaration (probably because this isn't how Element is meant to be used and the Array stuff isn't written yet?)

```python
p = Pointer(t,float32,attrs=[value_const])
print(ccode(p)) #ok
print(ccode(p[3])) #ok
print(ccode(p.as_Declaration())) #yay
print(ccode(Declaration(p))) #yay
print(ccode(Declaration(p[3]))) #sad face
print(ccode(Declaration(p[3], type=float32))) #sad face
```
outputs:
```c
t
t[3]
const float * t
const float * t
ValueError: C does not support untyped variables
ValueError: Unknown kwargs: {'type': FloatType(String('float32'), nbits=Integer(32), nmant=Integer(23), nexp=Integer(8))}
```

It feels funny to me that Element is not also a Variable? Elements can be declared, assigned to, and evaluated just like any other variable but with different meaning I guess.
```c
float x[3];
float x[3] = {1,2,3};
x[1] = 4;
float y = x[0]*x[1]*x[2];
```

**Comment by bjodah** [comment]
The way I've been thinking about it has been that `Element` represents a single element in some larger N-dimensional array (possibly 0-dimensional scalar). So the `Declaration` should be made for the larger N-dimensional array. The tricky part is how much we should assume with respect to the representation of that N-dimensional array. In fortran it is quite easy since N-dimensional arrays are part of the language:

https://github.com/bjodah/sympy/blob/d313e132167a82070e3fb06e9cbf173937f1e9ab/sympy/codegen/fnodes.py#L324

In C they could be a stack allocated (as in your suggested example), but they may also be heap allocated (pointer to `malloc`ed data). In C++ it might be a `new` allocated pointer (which would have to be `delete`:ed and not `free`d), or `std::unique_ptr<double[]>`, or ... (you get the picture).

Perhaps a `StackArray` in `.codegen.cnodes` would be useful?

Isn't possible to generate code which assigns a (scalar) value to an instance of `Element`?

I can see the confusion about `Element` not being a subclass of `Variable`, but I don't think the `Element` should be "declarable" (and hence shouldn't share that code of Variable). Perhaps the first
[__slot__](https://github.com/bjodah/sympy/blob/d313e132167a82070e3fb06e9cbf173937f1e9ab/sympy/codegen/ast.py#L1379) in Element should be renamed from "symbol" to "parent" (it is through this field I imagine the user could query e.g. datatype).

**Comment by stewpend0us** [comment]
What is the eventual goal of codegen? To be able to create any arbitrary code in any language? Or just to be able to write "mathematical" functions? I guess the idea of auto-generating code that calls malloc or new is mildly terrifying but also feels like it would not be needed for relatively simple "math" functions.

also if you would rather I go ask these questions in the main repo...please let me know.

**Comment by bjodah** [comment]
I'd say "mathematical" functions, e.g. "cosm1" (analogous to expm1). But also "mathematical functions" with a bit wider scope (see the test for Newton's method in test_algorithms).

I can see that calling malloc/free could be a bit scary and should probably not be the default. I'm a bit unsure on platform/os settings and their restriction on stacksize though?

This repo is a good place to ask questions on my branch. You're essentially reviewing the code so it is much appreciated! :-)

**Comment by bjodah** [comment]
Closing since sympy/sympy#13100 has been merged.
